# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 535)
        Dialog.setStyleSheet("/* Styl dla całego okna głównego (QWidget lub QMainWindow) */\n"
"QWidget {\n"
"    background-color: #2e2e2e; /* Ciemnoszary tło */\n"
"    color: #ffffff;           /* Biały tekst */\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* Style dla list (QListWidget) */\n"
"QListWidget {\n"
"    background-color: #3a3a3a; /* Trochę jaśniejsze tło dla lepszego kontrastu */\n"
"    border: 1px solid #5c5c5c;\n"
"    selection-background-color: #0078d7; /* Kolor zaznaczenia (niebieski) */\n"
"    selection-color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #0078d7;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Style dla etykiet (QLabel) */\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    padding: 2px 0;\n"
"}\n"
"\n"
"/* Style dla przycisków (QPushButton) */\n"
"QPushButton {\n"
"    background-color: #0078d7; /* Niebieskie tło */\n"
"    color: #ffffff;           /* Biały tekst */\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005a9e; /* Ciemniejszy niebieski po najechaniu */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003c6e; /* Jeszcze ciemniejszy po kliknięciu */\n"
"}\n"
"\n"
"/* Style dla GroupBox */\n"
"QGroupBox {\n"
"    border: 1px solid #5c5c5c;\n"
"    margin-top: 10px; /* Zostaw miejsce na tytuł */\n"
"    padding: 10px;\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    color: #ffffff;\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"/* Style dla pól wyboru (QCheckBox) */\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #5c5c5c;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #0078d7; /* Niebieski po zaznaczeniu */\n"
"    border: 1px solid #0078d7;\n"
"    image: url(path/to/check.png); /* Własna ikona zaznaczenia (opcjonalnie) */\n"
"}\n"
"\n"
"/* Style dla edytora tekstu (QTextEdit) */\n"
"QTextEdit {\n"
"    background-color: #3a3a3a;\n"
"    color: #ffffff;\n"
"    border: 1px solid #5c5c5c;\n"
"    padding: 5px;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.gridLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_box_main_list = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.check_box_main_list.setChecked(True)
        self.check_box_main_list.setObjectName("check_box_main_list")
        self.horizontalLayout.addWidget(self.check_box_main_list)
        self.check_box_draft_list = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.check_box_draft_list.setObjectName("check_box_draft_list")
        self.horizontalLayout.addWidget(self.check_box_draft_list)
        self.check_box_done_list = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.check_box_done_list.setObjectName("check_box_done_list")
        self.horizontalLayout.addWidget(self.check_box_done_list)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.not_important_list_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(10)
        self.not_important_list_name.setFont(font)
        self.not_important_list_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.not_important_list_name.setObjectName("not_important_list_name")
        self.verticalLayout_3.addWidget(self.not_important_list_name)
        self.draft_list = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.draft_list.setObjectName("draft_list")
        self.verticalLayout_3.addWidget(self.draft_list)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.done_list_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(10)
        self.done_list_name.setFont(font)
        self.done_list_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.done_list_name.setObjectName("done_list_name")
        self.verticalLayout_2.addWidget(self.done_list_name)
        self.done_list = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.done_list.setObjectName("done_list")
        self.verticalLayout_2.addWidget(self.done_list)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_list_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(10)
        self.main_list_name.setFont(font)
        self.main_list_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_list_name.setObjectName("main_list_name")
        self.verticalLayout_4.addWidget(self.main_list_name)
        self.main_list = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.main_list.setObjectName("main_list")
        self.verticalLayout_4.addWidget(self.main_list)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 2, 0, 1, 1)
        self.delete_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 390, 961, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.save_to_file_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.gridLayout_3.addWidget(self.save_to_file_button, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.calculate_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.calculate_button.setObjectName("calculate_button")
        self.gridLayout_3.addWidget(self.calculate_button, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.weight_spin_box = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget_2)
        self.weight_spin_box.setMaximum(999.99)
        self.weight_spin_box.setObjectName("weight_spin_box")
        self.verticalLayout_7.addWidget(self.weight_spin_box)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.height_spin_box = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget_2)
        self.height_spin_box.setMaximum(999.99)
        self.height_spin_box.setObjectName("height_spin_box")
        self.verticalLayout_5.addWidget(self.height_spin_box)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.bmi_value_label = QtWidgets.QLabel(parent=Dialog)
        self.bmi_value_label.setGeometry(QtCore.QRect(490, 500, 481, 21))
        self.bmi_value_label.setObjectName("bmi_value_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Dodaj do:"))
        self.check_box_main_list.setText(_translate("Dialog", "Głównej listy"))
        self.check_box_draft_list.setText(_translate("Dialog", "Roboczej listy"))
        self.check_box_done_list.setText(_translate("Dialog", "Zakończone"))
        self.not_important_list_name.setText(_translate("Dialog", "Robocza lista"))
        self.done_list_name.setText(_translate("Dialog", "Zakończone"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Napisz element do dodania"))
        self.main_list_name.setText(_translate("Dialog", "Główna Lista"))
        self.add_button.setText(_translate("Dialog", "Dodaj"))
        self.delete_button.setText(_translate("Dialog", "Usuń zaznaczone"))
        self.save_to_file_button.setText(_translate("Dialog", "Zapisz"))
        self.label.setText(_translate("Dialog", "Zapisz do pliku"))
        self.calculate_button.setText(_translate("Dialog", "Oblicz BMI"))
        self.label_2.setText(_translate("Dialog", "Waga"))
        self.label_3.setText(_translate("Dialog", "Wzrost"))
        self.bmi_value_label.setText(_translate("Dialog", "Twoje BMI wynosi:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
